---
- name: Ensure lsb_release is available
  apt:
    name: lsb-release
    state: present

- name: Install Docker dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present

# - name: Update apt cache after adding Docker repo
#   apt:
#     update_cache: yes
#     cache_valid_time: 3600

- name: Install Docker CE
  apt:
    name: docker-ce
    state: present

- name: Ensure Docker service is running
  service:
    name: docker
    state: started
    enabled: yes