---
- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Ensure directory exists for Docker Compose
  file:
    path: /tmp/cloud-infra/ansible 
    state: directory

- name: Start services using Docker Compose
  shell: |
    docker-compose build
    docker-compose down || true
    docker-compose up -d
  args:
    chdir: /tmp/cloud-infra/ansible 
