- name: Download Grafana tar
  get_url:
    url: https://dl.grafana.com/oss/release/grafana-9.2.4.linux-amd64.tar.gz
    dest: /tmp/grafana.tar.gz

- name: Extract Grafana
  unarchive:
    src: /tmp/grafana.tar.gz
    dest: /opt/
    remote_src: yes

- name: Symlink Grafana binary
  file:
    src: /opt/grafana-9.2.4/bin/grafana-server
    dest: /usr/local/bin/grafana-server
    state: link

- name: Copy systemd unit
  template:
    src: grafana-server.service.j2
    dest: /etc/systemd/system/grafana-server.service
    mode: '0644'

- name: Start and enable Grafana
  systemd:
    name: grafana-server
    enabled: yes
    state: started

- name: Wait for Grafana API
  uri:
    url: http://localhost:3000/api/health
    method: GET
    status_code: 200
  retries: 10
  delay: 5
  register: grafana_health
  until: grafana_health.status == 200

- name: Add Prometheus as Grafana data source
  uri:
    url: http://admin:admin@localhost:3000/api/datasources
    method: POST
    headers:
      Content-Type: application/json
    body_format: json
    body: |
      {
        "name": "Prometheus",
        "type": "prometheus",
        "url": "http://localhost:9090",
        "access": "proxy",
        "basicAuth": false
      }
    status_code: 200
    ignore_errors: true
