- name: Create user
  user:
    name: prometheus
    shell: /usr/sbin/nologin
    system: yes

- name: Download Prometheus tar
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.31.1/prometheus-2.31.1.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes

- name: Copy Prometheus binary
  copy:
    remote_src: yes
    src: /opt/prometheus-2.31.1.linux-amd64/prometheus
    dest: /usr/local/bin/prometheus
    mode: '0755'

- name: Create config directory
  file:
    path: /etc/prometheus
    state: directory

- name: Add Prometheus config
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    mode: '0644'
    owner: prometheus
    group: prometheus

- name: Setup systemd service
  template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: '0644'

- name: Enable and start Prometheus
  systemd:
    name: prometheus
    enabled: yes
    state: started
