name: Terraform Plan

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./cloud-infra/terraform-infra

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_GH_TOKEN: ${{ secrets.GH_TOKEN }}
      TF_VAR_GH_USERNAME: ${{ secrets.GH_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.6

      - name:  Verify Terraform version
        run: terraform --version

      - name: Terraform Init
        run: terraform init \
          -backend=true \
          -backend-config="bucket=jayant-test" \
          -backend-config="key=infra/terraform.tfstate" \
          -backend-config="region=ap-east-1"

      - name: 🔍 Terraform Plan
        run: terraform plan
